import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>tailcom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-red-600 font-bold text-3xl">Next tailcom</h1>
    </>
  );
}
